### ISSUE TITLE
the tSNR range

### ISSUE THREAD

**Issue by Ernest861** [CPernet/spmup#14]
Hi, Prof. Cyril Pernet 

Thanks for your scripts, it is easy to calculate the SNR in MRI.
I run the spmup_temporalSNR in my resting-state data (after realign and normalize ) and find the results range looks very small (nanmean(nanmean(data,1))=-4.1118e-10, sdtGM=44.42). it may be my mask problem? 

GM: -9.2565e-12
                 WM: -8.0658e-11
                CSF: 1.6624e-10
     Background_raw: [290×271633 double]
         Background: -5.3686e-12
            average: -1.9041e-12
              image: -1.9626e-11
     SNR02tSNR_corr: 0.7277
    SNR02tSNR_ratio: 0.9953
        signal_mean: 0.0000e+00 - 1.1248e-09i
                roi: [1×1 struct]
[Templates.zip](https://github.com/CPernet/spmup/files/4861638/Templates.zip)

can you have a look?

Thanks

Zheng Hui
Shanghai Mental Health Center

**Comment by CPernet** [comment]
hi,

i could not read the images - i suggest to use nifti which helps with orientation and somply check with spm check reg your mask images are ok - let me know how it goes
