### ISSUE TITLE
spmup_censoring output txt file does not include FD, RMS and global values

### ISSUE THREAD

**Issue by Remi-Gau** [CPernet/spmup#15]
Unless I am mistaken the spmup_censoring will only save a text file with:
- motion regressors  + censoring regressors
or
- motion regressors + their voltera expansion + censoring regressors

But it will not include the framewise displacement, RMS or the global values even though those are used to generate the censoring regressors.

Is that intentional or should it be fixed?

https://github.com/CPernet/spmup/blob/198c980d6d7520b1a996f0e56269e2ceab72cc83/QA/spmup_censoring.m#L67

**Comment by CPernet** [comment]
well yes but this should be called from https://github.com/CPernet/spmup/blob/master/QA/spmup_first_level_qa.m and/or https://github.com/CPernet/spmup/blob/master/QA/spmup_realign_qa.m which defines the different stuffs you want - if you want censoring then this function is called
