### ISSUE TITLE
where did the carpet plot go? ;-p

### ISSUE THREAD

**Issue by Remi-Gau** [CPernet/spmup#16]
Just wondering if it was intentional to remove the carpet plot function and not re-add it later when the files were moved into sub folders ?

https://github.com/CPernet/spmup/commit/58e94c17ea0c1e8e878461f9aa191085a397f186

**Comment by CPernet** [comment]
good point, i guess this is useful no matter the design anyway -- it's here https://github.com/CPernet/spmcon/blob/master/spmup_timeseriesplot.m as i moved away connectivity stuff ; maybe we should copy it into the plot subfolder

**Comment by Remi-Gau** [comment]
spmcon is a private repo, right?

If you want I can grab the file from the history and put it in the subfolder.

**Comment by CPernet** [comment]
ah could be - mostly because it's half baked ; yes please do
