### ISSUE TITLE
spmup_temporalSNR figure bug

### ISSUE THREAD

**Issue by CPernet** [CPernet/spmup#23]
mmh haven't looked properly at the merge but figures are all messed up, bits of code at the wrong place

**Comment by Remi-Gau** [comment]
Thanks for the ping.
Will have a look.

**Comment by Remi-Gau** [comment]
trouble seems to have started  here: https://github.com/CPernet/spmup/commit/04785501f1c8d558664865b95c6bd4039cc531c6
