### ISSUE TITLE
Framewise displacement is not saved

### ISSUE THREAD

**Issue by Remi-Gau** [CPernet/spmup#40]
this is a regression 

this had been fixed in #26 

will investigate and make the tests run in CI so this bug is less likely to come back from the dead

**Comment by CPernet** [comment]
that's correct - FD is not in there on purpose because it makes not sense to do so 319c2908a373bad0edaa1d299d06d0bcce371a7e

**Comment by Remi-Gau** [comment]
So currently there is no way for `spmup_realign_qa` to return the values of framewise displacement?

**Comment by CPernet** [comment]
but not saved

**Comment by Remi-Gau** [comment]
gotcha

**Comment by Remi-Gau** [comment]
will close this and the PR and see If I can actually reuse this in my code
