### ISSUE TITLE
SPM12 MNI space is `IXI549Space` not `MNI152NLin2009`

### ISSUE THREAD

**Issue by Remi-Gau** [CPernet/spmup#42]
See IXI549Space in this table

https://bids-specification.readthedocs.io/en/latest/appendices/coordinate-systems.html#standard-template-identifiers

This should probably be changed in the bids pipeline

**Comment by CPernet** [comment]
better? https://github.com/CPernet/spmup/commit/caa50d2886e1cf5af2b0f07ae0ddf951fcc73a15

**Comment by Remi-Gau** [comment]
all good

**Comment by CPernet** [comment]
if normalizing using the EPI-norm option (old fashion EPI data to EPI template) what is the space? MNI152Lin

**Comment by Remi-Gau** [comment]
BIDS spec says so...

Am the one who edited this table to match some info coming from nidm that Satra and Camille had worked on. 

So fairly confident.

**Comment by CPernet** [comment]
+1
