### ISSUE TITLE
Field Maps missing - needs filter

### ISSUE THREAD

**Issue by CPernet** [CPernet/spmup#43]
@Remi-Gau is this last [fix](https://github.com/CPernet/spmup/commit/68b8a5123399fbeb2f8d107c604aa3cec9370ab9) I added some ugly code to look for missing files in fmap !!! spm_BIDS or bids.layout same errors

The issue arises when you have many types of field maps for instance some dir-AP_phasediff.nii and dir-PA_phasediff.nii in the same folder (maybe solved if there is no intended for, but in my case there isn't), also doesn't list all if some _phasediff.nii and _epi.nii in the same folder (yeh had fun ... thx for @fishpm). I'll make some 0kb data to try debugging but I did not want to mess up guillaumes' regex. Should I make a branch in bids-matlab with a subdir for testing?

**Comment by Remi-Gau** [comment]
A dummy example dataset with truncated data and the commands you tried to run would defo be much appreciated indeed.

**Comment by Remi-Gau** [comment]
Also am I correct in reading the code that you are trying to access the structure of the layout directly rather than using the query function of spm_bids or bids matlab?

**Comment by Remi-Gau** [comment]
I do remember that some suffixes and entities were not supported by spm_bids a while back.
BIDS matlab relies on the schema, so it should hopefully get less confused. In theory.

**Comment by Remi-Gau** [comment]
> Also am I correct in reading the code that you are trying to access the structure of the layout directly rather than using the query function of spm_bids or bids matlab? 

Asking this because if that is the case you may be making more difficult I think.

Should definitely be easier to use the query function of spm_bids or bids matlab.

Also because the high level api of those query functions should remain fairly stable whereas the internal structure of the may change (which could break your code if you are trying to access it directly).

Sorry if that was not clear in the bids matlab doc. Should make harder to miss.

**Comment by CPernet** [comment]
> I do remember that some suffixes and entities were not supported by spm_bids a while back. BIDS matlab relies on the schema, so it should hopefully get less confused. In theory.

all files can be found if not bundled

**Comment by CPernet** [comment]
> > Also am I correct in reading the code that you are trying to access the structure of the layout directly rather than using the query function of spm_bids or bids matlab?
> 
> Asking this because if that is the case you may be making more difficult I think.
> 
> Should definitely be easier to use the query function of spm_bids or bids matlab.
> 
> Also because the high level api of those query functions should remain fairly stable whereas the internal structure of the may change (which could break your code if you are trying to access it directly).
> 
> Sorry if that was not clear in the bids matlab doc. Should make harder to miss.

you cannot query something that is not indexed! the new code update thew missing files, then you can query and unpack all the files

**Comment by Remi-Gau** [comment]
Juste  curious. 
Is this also an issue with the dev branch of bids matlab?

**Comment by CPernet** [comment]
was already on dev

**Comment by Remi-Gau** [comment]
Okidoki.
Defo curious to see the bug in action.

**Comment by CPernet** [comment]
ok done https://github.com/bids-standard/bids-matlab/pulls (sorry it has an older face rep commit in thee too)

**Comment by Remi-Gau** [comment]
Thanks and no worries I will try to sort things out.

Travelling at the moment but should be able to habe a look tomorrow.
